name: base
channels:
  - nvidia
  - pytorch3d
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=*=*cuda11.8*
  - pytorch-cuda=11.8
  - pytorch3d
  - pip
  - pip:
    - numpy
    - -r requirements.txt
#   - mediapipe
#   - opencv-python
#   - wandb